color: null
fieldLayouts:
  f37a11d8-f5f3-4d7f-904b-1712dff37a35:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T16:41:27+00:00'
            elementCondition: null
            fieldUid: 07691201-0ed1-4d82-b589-924f9a554251 # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e22d9f64-f99b-463d-8709-6744d46baa72
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T16:41:27+00:00'
            elementCondition: null
            fieldUid: 4c268a71-4ff4-435e-a458-8981023170a7 # Page Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 884cc747-1c59-46ca-9f77-06ce6f07694e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T16:41:27+00:00'
            elementCondition: null
            fieldUid: 91c7ddbc-2020-4942-9a2c-27ac67844247 # Page Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02e2605d-dcb0-4bd5-b844-9c58d9997b76
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d79bb2c1-fdb3-4eda-82c5-067e882ba9b1
        userCondition: null
handle: Default
hasTitleField: false
icon: ''
name: Default
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
