color: pink
fieldLayouts:
  2c4660e8-4ac1-435f-8acd-e3a20a4e8f56:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-25T18:32:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Drinks Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9d85ec8b-6751-436d-b627-e5508ae2a704
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-25T18:30:56+00:00'
            elementCondition: null
            fieldUid: c536bd9d-4e73-42fc-8350-0b9a674892b3 # Introductions
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a4dbe7e-ad0f-4e58-bea5-0b7c78e583b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-25T18:30:56+00:00'
            elementCondition: null
            fieldUid: 91c7ddbc-2020-4942-9a2c-27ac67844247 # Page Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90faee13-8879-4ff5-a36c-3a4dd8d28fe6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T04:49:40+00:00'
            elementCondition: null
            fieldUid: dcdaacb7-f1cd-4656-b054-2733679ab473 # Drinks Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04f5ee8b-f503-423c-8872-51b59feebdca
            userCondition: null
            warning: null
            width: 100
        name: Drinks
        uid: d7990fcb-dae5-43d3-a2ec-b9c7f76bbf17
        userCondition: null
handle: Drinks
hasTitleField: true
icon: beer-mug
name: Drinks
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
