altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c77ecb64-2698-4b22-b4a9-69acdf1d3430:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T04:34:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: daee7cad-f990-4bf9-9f4e-f2d851312969
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ee34f0e3-7c57-4838-93d0-cd6b69b44c6a
        userCondition: null
fs: localAssets
handle: drinks
name: Drinks
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
